config/routes.rb
Rails.application.routes.draw do

  root to: "books#index"

  resources :books
  resources :tags

  get '/filter_books', to: "books#index"
  post '/filter_books', to: "books#filter_books"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assign_book_tag.rb
class AssignBookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :assign_book_tags
  has_many :tags, through: :assign_book_tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :assign_book_tags
  has_many :books, through: :assign_book_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
  end

  def filter_books
    @books = [];

    @books = Book.all if !params["filter_tag"].present? && !params["filter_price"].present?
    get_book if params["filter_tag"].present? && params["filter_price"].present?
    get_book_price if !params["filter_tag"].present? && params["filter_price"].present?
    get_book_tag if params["filter_tag"].present? && !params["filter_price"].present?
   
    render 'index'
  end

  def get_book_price
    price = params["filter_price"].split("-")
    @selected_price = [params["filter_price"],params["filter_price"]]
    @books = Book.where('price BETWEEN ? AND ?',price[0].to_i,price[1].to_i)
  end

  def get_book_tag
    @tags = Tag.where(name: params["filter_tag"])

    @selected_tags = params["filter_tag"]
    @tags.each do |tag|
      @books = @books + tag.books
    end
    @books = @books.uniq
  end

  def get_book
    @books_tag = [];
    @tags = Tag.where(name: params["filter_tag"])
    @selected_tags = params["filter_tag"]
    @tags.each do |tag|
      @books_tag = @books_tag + tag.books
    end

    price = params["filter_price"].split("-")
    @selected_price = [params["filter_price"],params["filter_price"]]
    @books_price = Book.where('price BETWEEN ? AND ?',price[0].to_i,price[1].to_i)
    
    @books = @books_price & @books_tag.uniq
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def edit
    @tag = Tag.find(params[:id])
    @books = Book.all
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.books.destroy_all
    params[:book_ids].each do |book_id|
      book = Book.find(book_id)
      AssignBookTag.create(book_id: book.id , tag_id: @tag.id)
    end
    flash[:notice] = "Tag added to selectced book successfully"
    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  
  def get_tags(book)
    tags = '';
    book.tags.pluck(:name).each do |tag_name|
      tags = tag_name + ' ' +tags;
    end
    return tags
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  
  def get_checked(book)
    book.tags.pluck(:id).include?(@tag.id)
  end
end

app/views/books/_filter_by.html.erb
<%= form_with url: filter_books_path, method: :post do |form| %>
<div class="row mt-5">
  <div class="col-2">
  </div>
  <div class="col-2">
    Filter books by : 
  </div>
  <div class="col-2">
    Price : 
    <%= select_tag "filter_price", options_for_select([['0-50','0-50'],['50-100','50-100'],['100-150','100-150'],['150-200','150-200'],['more than 200','201-100000']],selected:@selected_price), { class: 'form-control', prompt: "Select Price"}%>
  </div>
  <div class="col-2">
    Tags : 
    <%= select_tag "filter_tag", options_for_select(Tag.all.pluck(:name),selected:@selected_tags), { class: 'form-control',multiple: true}%>
  </div>
  <div class="col-2">
    <%= form.submit 'Filter Books', class: 'btn btn-primary ml-5' %>
  </div>
</div>
<% end %>

app/views/books/index.html.erb
<%= render 'filter_by' %>
<table class="table table-striped col-md-10 mx-auto mt-5" id="movies">
  <thead>
    <tr>
      <th>Book Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Tags</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= book.title %>
        </td>
        <td>
          <%= book.description %>
        </td>
        <td>
          <%= book.price %>
        </td>
        <td>
          <%= get_tags(book) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_flash_notice.html.erb
<% flash.each do |type, msg| %>
  <% unless type == 'timedout' %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/books">Books <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/tags">Tags</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>BookTag</title>
  </head>
  <body class="add_bg">
  <section class="content-container">
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'layouts/flash_notice' %>
    <%= yield %>
  </section>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tags/edit.html.erb
<%= form_with url: tag_path(@tag), method: :patch do |form| %>
  <table class="table table-striped col-md-10 mx-auto mt-5" id="movies">
    <thead>
      <tr>
        <th>Book Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Select Book</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= book.title %>
          </td>
          <td>
            <%= book.description %>
          </td>
          <td>
            <%= book.price %>
          </td>
          <td>
            <%= check_box_tag "book_ids[]", book.id, get_checked(book) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= form.submit :submit, class: 'btn btn-primary ml-5' %>
<% end %>

app/views/tags/index.html.erb
<table class="table table-striped col-md-10 mx-auto mt-5" style="width:50%" id="movies">
  <thead>
    <tr>
      <th>Tag Name</th>
      <th>Total number of Books</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td>
          <%= tag.name %>
        </td>
        <td>
          <%= tag.books.count %>
        </td>
        <td>
          <%= link_to 'Assign Tag to Book', edit_tag_path(tag), :class => 'btn btn-primary ml-5' %>   
        </td>
      </tr>
    <% end %>
  </tbody>
</table>